### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: __MODEL_PATH__
adapter_name_or_path: __SAVE_DIR__
template: qwen3_vl
trust_remote_code: true

### export
export_dir: __MERGED_DIR__
export_size: 5
export_device: cpu
export_legacy_format: false
